import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import LoginButton from '@/component/header/LoginButton';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogoutButton from '@/component/header/LogoutButton';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions); // 현재 로그인한 유저의 정보
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          {session?.user === null ? <LoginButton /> : <LogoutButton />}
        </div>
        {children}
      </body>
    </html>
  );
}
